config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('watchlist/', include('watchlist.urls'))
]

watchlist/urls.py
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path
from django.views.generic.base import RedirectView


from watchlist import views

app_name = "watchlist"

urlpatterns = [
    path('home/', views.home, name="home"),
    path('forms/', views.forms, name='forms'),
    path('forms/movies_form/', views.forms_movies, name='forms_movies'),
    path('forms/people_form/', views.forms_people, name='forms_people'),
    path('generated_by_movies/', views.result_movies, name='result_movies'),
    path('generated_by_people/', views.result_people, name='result_people'),

]

watchlist/models.py
from datetime import datetime

from django.db import models

from database import create_choices, get_max_votes_num
from functions import cur_date
from watchlist.validators import MaxValueValidator, MinValueValidator


class Movies(models.Model):
    CHOICES_GENRES = create_choices()
    CHOICES_GENRES.insert(0, ('', ''))

    movie_rating = models.FloatField(validators=[MinValueValidator(1.0),
                                           MaxValueValidator(10.0)
                                           ],
                               default='',
                               null=True
                               )
    movie_votes = models.IntegerField(validators=[MinValueValidator(1000),
                                            MaxValueValidator(get_max_votes_num())
                                            ],
                                blank=True,
                                null=True
                                )
    genre = models.CharField(max_length=32,
                             choices=CHOICES_GENRES,
                             blank=True,
                             null=True
                             )
    prod_year = models.IntegerField(validators=[MinValueValidator(1960),
                                                MaxValueValidator(cur_date())
                                                ],
                                    blank=True,
                                    null=True
                                    )
    number_of_movies_to_choose = models.IntegerField(validators=[MinValueValidator(1),
                                                                 MaxValueValidator(30)
                                                                 ]
                                                     )


class People(models.Model):
    CHOICES_ROLES = [
        ("actor", "Actor"),
        ("actress", "Actress"),
        ("director", "Director")
    ]
    CHOICES_ROLES.insert(0, ('', ''))
    current_date = datetime.today().year

    people_rating = models.FloatField(validators=[MinValueValidator(1.0),
                                           MaxValueValidator(10.0)
                                           ],
                               default='',
                               null=True
                               )
    people_votes = models.IntegerField(validators=[MinValueValidator(1000),
                                            MaxValueValidator(get_max_votes_num())
                                            ],
                                blank=True,
                                null=True
                                )
    role = models.CharField(max_length=16,
                            choices=CHOICES_ROLES,
                            null=True
                            )
    name = models.CharField(max_length=128, default='', blank=True, null=True)
    birth_year = models.IntegerField(validators=[MinValueValidator(1900),
                                                 MaxValueValidator(cur_date())
                                                 ],
                                     null=True
                                     )
    number_of_movies_to_choose = models.IntegerField(validators=[MinValueValidator(1),
                                                                 MaxValueValidator(30)
                                                                 ]
                                                     )

watchlist/forms.py
from django import forms

from database import get_max_votes_num
from functions import cur_date
from watchlist.models import Movies, People


class MoviesForm(forms.ModelForm):
    class Meta:
        model = Movies
        fields = "__all__"
        labels = {
            "movie_rating": "Average rating (min)",
            "movie_votes": "Number of votes (min)",
            "genre": "Movie genre",
            "prod_year": "Year of production (min)"
        }
        widgets = {
            "movie_rating": forms.TextInput(attrs={"placeholder": "1 - 10"}),
            "movie_votes": forms.TextInput(attrs={"placeholder": f"1000 - {get_max_votes_num()}"}),
            "prod_year": forms.TextInput(attrs={"placeholder": f"1960 - {cur_date()}"})
        }


class PeopleForm(forms.ModelForm):
    class Meta:
        model = People
        fields = "__all__"
        labels = {
            "people_rating": "Average rating (min)",
            "people_votes": "Number of votes (min)",
            "role": "Role in the movie",
            "name": "Name of person",
            "birth_year": "Year of birth"
        }
        widgets = {
            "people_rating": forms.TextInput(attrs={"placeholder": "1 - 10"}),
            "people_votes": forms.TextInput(attrs={"placeholder": f"1000 - {get_max_votes_num()}"}),
            "name": forms.TextInput(attrs={"placeholder": "John Doe/Bruce Lee"}),
            "birth_year": forms.TextInput(attrs={"placeholder": f"1900 - {cur_date()-1}"})
        }


class RadioSelect(forms.Form):
    choices = (('movies', 'Filter by movies'), ('people', 'Filter by people'))
    radio_select = forms.ChoiceField(choices=choices, initial=0, widget=forms.RadioSelect)

watchlist/views.py
from copy import copy

import requests
from bs4 import BeautifulSoup
from django.shortcuts import redirect
from django.shortcuts import render

from statement import get_movies, get_people, drop_tables
from watchlist.forms import MoviesForm, PeopleForm, RadioSelect


def home(request):
    return render(
        request,
        'watchlist/home.html'
    )


def forms(request):
    radio_form = RadioSelect()

    return render(
        request,
        'watchlist/forms.html',
        context={
            "radio_form": radio_form
        }
    )


def forms_movies(request):
    if request.method == "POST":

        movies_form = MoviesForm(request.POST)

        if movies_form.is_valid():
            movies_form.save()

        return redirect('watchlist:result_movies')

    movies_form = MoviesForm()

    return render(
        request,
        'watchlist/forms_movies.html',
        context={
            "movies_form": movies_form,
        }
    )


def forms_people(request):
    if request.method == "POST":

        people_form = PeopleForm(request.POST)

        if people_form.is_valid():
            people_form.save()

        return redirect('watchlist:result_people')

    people_form = PeopleForm()

    return render(
        request,
        'watchlist/forms_people.html',
        context={
            "people_form": people_form,
        }
    )


def result_movies(request):
    list_of_movies = get_movies()

    for idx, movie in enumerate(copy(list_of_movies)):
        list_of_movies[idx] = list(list_of_movies[idx])
        list_of_movies[idx][2] = 'https://www.imdb.com/title/' + movie[2] + '/'
        list_of_movies[idx].append('https://www.imdb.com/title/' + movie[2] + '/mediaindex')

    list_of_urls = [images_url[3] for images_url in list_of_movies]

    list_of_sources = []

    for url in list_of_urls:
        response = requests.get(url)

        soup = BeautifulSoup(response.content, "html.parser")

        images = soup.find_all("img", attrs={"class": "poster"})
        image_src = images[0]['src']

        list_of_sources.append(image_src)

    list_of_movies = [list_of_movies[i][:3] + [list_of_sources[i]] for i in range(len(list_of_movies))]

    drop_tables()

    return render(
        request,
        'watchlist/result_movies.html',
        context={
            "list_of_movies": list_of_movies
        }
    )


def result_people(request):
    list_of_people = get_people()

    for idx, movie in enumerate(copy(list_of_people)):
        list_of_people[idx] = list(list_of_people[idx])
        list_of_people[idx][2] = 'https://www.imdb.com/title/' + movie[2] + '/'
        list_of_people[idx].append('https://www.imdb.com/title/' + movie[2] + '/mediaindex')

    list_of_urls = [images_url[3] for images_url in list_of_people]

    list_of_sources = []

    for url in list_of_urls:
        response = requests.get(url)

        soup = BeautifulSoup(response.content, "html.parser")

        images = soup.find_all("img", attrs={"class": "poster"})
        image_src = images[0]['src']

        list_of_sources.append(image_src)

    list_of_people = [list_of_people[i][:3] + [list_of_sources[i]] for i in range(len(list_of_people))]

    drop_tables()

    return render(
        request,
        'watchlist/result_people.html',
        context={
            "list_of_people": list_of_people
        }
    )

watchlist/templates/watchlist/forms.html
{% extends 'watchlist/layout.html' %}

{% block title %}
Watchlist generator
{% endblock %}

{% block section %}
<div class="text-box" id="forms_tmp">
    <h1>Filter zone</h1>

    <p>In this section, you can choose whether you want to filter the videos by cinematic or personal features.
        You can choose only one option. After clicking the button, you will see the appropriate form
        that must be completed.</p>
    <p>Fields with a note (min) mean that you enter the minimum value from which the films will be filtered
        for the selected parameter. Rating and number of videos are fields that you MUST fill in,
        the rest is optional. However, take into account that when filtering people, be sure to enter their
        year of birth (there are duplicates of people with the same names and surnames in the database).</p>

    <h4>Which filtering option would you like to choose?</h4>

    {% for i in radio_form %}
        {{ i }}
    {% endfor %}

    <a onclick="formRedirect()" id="radio_redirect" class="hero-btn">This is my choice!</a>
</div>
{% endblock %}

{% block body %}
<script>
    function formRedirect(){
        var radioValue = document.querySelector('input[name="radio_select"]:checked').value;
        if (radioValue === 'movies')
        {
            document.getElementById("radio_redirect").onclick = function ()
            {
            window.location.href = "{% url 'watchlist:forms_movies' %}"
            };
        }
        else if (radioValue === 'people')
        {
            document.getElementById("radio_redirect").onclick = function ()
            {
            window.location.href = "{% url 'watchlist:forms_people' %}"
            };
        }
    }
</script>
{% endblock %}

watchlist/templates/watchlist/forms_movies.html
{% extends 'watchlist/layout.html' %}

{% block title %}
Watchlist generator
{% endblock %}

{% block section %}
<div class="text-box">
    <h1>Filter by movie zone</h1>
    <h4>Reminder</h4>
    <p>Fields with a note (min) mean that you enter the minimum value from which the films will be
        filtered for the selected parameter. Rating, number of votes and number of videos are fields that you need
        to fill in, the rest is optional. </p>
</div>
{% endblock %}

{% block body %}
    <form id="form_movies" method="POST">
        {% csrf_token %}
        {{ movies_form.as_p }}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

watchlist/templates/watchlist/forms_people.html
{% extends 'watchlist/layout.html' %}

{% block title %}
Watchlist generator
{% endblock %}

{% block section %}
<div class="text-box">
    <h1>Filter by people zone</h1>
    <h4>Reminder</h4>
    <p>Fields with a note (min) mean that you enter the minimum value from which the films will be
        filtered for the selected parameter. Rating, number of votes and number of videos are fields that you need
        to fill in, the rest is optional. Keep in mind that you have to be sure to enter person's year of birth
        (there are duplicates of people with the same names and surnames in the database, so the person
        you might want to filter by may not be the one you are looking for).</p>
</div>
{% endblock %}

{% block body %}
    <form id="form_people" method="POST">
        {% csrf_token %}
        {{ people_form.as_p }}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

watchlist/templates/watchlist/home.html
{% extends 'watchlist/layout.html' %}

{% block title %}
Watchlist generator
{% endblock %}

{% block section %}
<div class="text-box">
    <h1 style="margin-top: 20%">Welcome to the watchlist generator!</h1>

    <p>This generator was created using databases provided by IMDb.
        Based on the filters selected in the appropriate form on the next page,
        a list of films of a given length is generated. You can draw films depending on the average rating,
        genre and year of production or the average rating and your favorite director/actor.</p>

    <h4>Would you like to generate some movies?</h4>
    <a href="{% url 'watchlist:forms' %}" class="hero-btn">Click here to begin</a>
</div>
{% endblock %}

watchlist/templates/watchlist/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="with=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'watchlist/css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;600;700&display=swap"
          rel="stylesheet">

</head>
<body id="bg" style="background-image: url({% static 'watchlist/images/cinema.png' %})");>
        <nav>
            <div class="nav-links">
                <ul>
                    <li><a href="{% url 'watchlist:home' %}">HOME</a></li>
                    <li><a href="{% url 'watchlist:forms' %}">FORMS</a></li>
                </ul>
            </div>
        </nav>
    {% block section %}
    {% endblock %}

    {% block body %}
    {% endblock %}
</body>
</html>

watchlist/templates/watchlist/result.html
{% extends 'watchlist/layout.html' %}

{% block title %}Generated watchlist{% endblock %}

{% block section %}
<div class="text-box">
    <h1>Your list</h1>
</div>
{% endblock %}

{% block body %}
<div>
    <table class="flowTable">
        {% for title, prod_year, movie_url, image_src in list_of_movies %}
            <tr>
                <td> <a href="{{ movie_url }}"><img src="{{ image_src }}" alt="poster"></a></td>
                <td> {{ title }} </td>
                <td> {{ prod_year }} </td>
                <td> <a href="{{ movie_url }}"> Link to the movie </a></td>
            </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

watchlist/templates/watchlist/result_movies.html
{% extends 'watchlist/layout.html' %}

{% block title %}Generated watchlist{% endblock %}

{% block section %}
<div class="text-box">
    <h1>Your list</h1>
    <br>
</div>
{% endblock %}

{% block body %}
<div>
    <table class="flowTable">
        {% for title, prod_year, movie_url, image_src in list_of_movies %}
            <tr>
                <td> <a href="{{ movie_url }}"><img src="{{ image_src }}" alt="poster"></a></td>
                <td> {{ title }} </td>
                <td> {{ prod_year }} </td>
                <td> <a href="{{ movie_url }}"> Link to the movie </a></td>
            </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

watchlist/templates/watchlist/result_people.html
{% extends 'watchlist/layout.html' %}

{% block title %}Generated watchlist{% endblock %}

{% block section %}
<div class="text-box">
    <h1>Your list</h1>
</div>
{% endblock %}

{% block body %}
<div>
    <table class="flowTable">
        {% for title, prod_year, movie_url, image_src in list_of_people %}
            <tr>
                <td> <a href="{{ movie_url }}"><img src="{{ image_src }}" alt="poster"></a></td>
                <td> {{ title }} </td>
                <td> {{ prod_year }} </td>
                <td> <a href="{{ movie_url }}"> Link to the movie </a></td>
            </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}